name: Build Chrome Extension

on:
  workflow_dispatch:          # 手动运行
  push:
    branches: [main]          # 每次 push 到 main 也自动发版

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # 允许写 release
    steps:
      - uses: actions/checkout@v4

      # 1. 自动生成一个带时间戳的 tag
      - name: Generate tag
        id: tag
        run: |
          TAG="v$(date +%Y%m%d-%H%M%S)"
          git tag $TAG
          git push origin $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # 2. 打包
      - name: Pack
        run: |
          zip -r chrome-ext-${{ steps.tag.outputs.tag }}.zip . \
            -x '*.git*' '.github/*'

      # 3. 发布 Release
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: chrome-ext-${{ steps.tag.outputs.tag }}.zip
          generate_release_notes: true
